[package]
name = "monero-wasm"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }
